services:
  opencloud:
    image: 'opencloudeu/opencloud:7.2.4'
    command:
      - '-c'
      - 'opencloud init || true; opencloud server'
    entrypoint:
      - '/bin/sh'
    user: '1000:1000'
    volumes:
      - '${APP_DATA_DIR}/data/opencloud/config:/etc/opencloud'
      - '${APP_DATA_DIR}/data/opencloud/data:/var/lib/opencloud'
    environment:
      - 'OC_URL=${APP_PROTOCOL}://${APP_DOMAIN}'
      - 'OC_LOG_LEVEL=info'
      - 'OC_LOG_COLOR=true'
      - 'OC_LOG_PRETTY=true'
      - 'PROXY_TLS=false'
      - 'OC_INSECURE=${OC_INSECURE}'
      - 'PROXY_ENABLE_BASIC_AUTH=false'
      - 'IDM_CREATE_DEMO_USERS=false'
      - 'IDM_ADMIN_PASSWORD=tipi'
      - 'FRONTEND_ARCHIVER_MAX_SIZE=10000000000'
      - 'FRONTEND_CHECK_FOR_UPDATES=true'
      - 'PROXY_CSP_CONFIG_FILE_LOCATION=/etc/opencloud/csp.yaml'
      - 'OC_PASSWORD_POLICY_BANNED_PASSWORDS_LIST=banned-password-list.txt'
      - 'OC_SHARING_PUBLIC_SHARE_MUST_HAVE_PASSWORD=true'
      - 'OC_SHARING_PUBLIC_WRITEABLE_SHARE_MUST_HAVE_PASSWORD=false'
      - 'OC_PASSWORD_POLICY_DISABLED=false'
      - 'OC_PASSWORD_POLICY_MIN_CHARACTERS=8'
      - 'OC_PASSWORD_POLICY_MIN_LOWERCASE_CHARACTERS=1'
      - 'OC_PASSWORD_POLICY_MIN_UPPERCASE_CHARACTERS=1'
      - 'OC_PASSWORD_POLICY_MIN_DIGITS=1'
      - 'OC_PASSWORD_POLICY_MIN_SPECIAL_CHARACTERS=1'
      - 'PROXY_HTTP_ADDR=0.0.0.0:9200'
    logging:
      driver: 'local'
    x-runtipi:
      internal_port: 9200
      is_main: true
x-runtipi:
  schema_version: 2
